adv: shoemakd.adventure.c
	gcc -std=c89 -o shoemakd.adventure shoemakd.adventure.c
rooms: shoemakd.buildrooms.c
	gcc -std=c89 -o shoemakd.buildrooms shoemakd.buildrooms.c
clean:
	rm -rf *.o shoemakd.adventure shoemakd.buildrooms shoemakd.rooms.1*
