adv: shoemakd.adventure.c
	gcc -std=c89 -o shoemakd.adventure shoemakd.adventure.c -lpthread
rooms: shoemakd.buildrooms.c
	gcc -std=c89 -o shoemakd.buildrooms shoemakd.buildrooms.c
clean:
	rm -rf *.o shoemakd.adventure shoemakd.buildrooms shoemakd.rooms.6*
	rm -rf *.o shoemakd.adventure shoemakd.buildrooms shoemakd.rooms.7*
	rm -rf *.o shoemakd.adventure shoemakd.buildrooms shoemakd.rooms.8*
	rm -rf *.o shoemakd.adventure shoemakd.buildrooms shoemakd.rooms.9*
	rm -rf *.o shoemakd.adventure shoemakd.buildrooms shoemakd.rooms.3*
	rm -rf *.o shoemakd.adventure shoemakd.buildrooms shoemakd.rooms.2*
